const { contextBridge, ipcRenderer } = require("electron");

contextBridge.exposeInMainWorld("vivid", {
  getStatus: () => ipcRenderer.invoke("launcher:get-status"),
  getSettings: () => ipcRenderer.invoke("launcher:get-settings"),
  saveDiscordWebhook: (value) => ipcRenderer.invoke("launcher:save-discord-webhook", value),
  saveDiscordSettings: (value) => ipcRenderer.invoke("launcher:save-discord-settings", value),
  testDiscord: (value) => ipcRenderer.invoke("launcher:test-discord", value),
  install: () => ipcRenderer.send("launcher:install"),
  update: (options) => ipcRenderer.send("launcher:update", options),
  checkUpdates: (options) => ipcRenderer.invoke("launcher:check-updates", options),
  installLauncherUpdate: () => ipcRenderer.invoke("launcher:install-launcher-update"),
  saveUpdateSettings: (value) => ipcRenderer.invoke("launcher:save-update-settings", value),
  uninstallLauncher: () => ipcRenderer.invoke("launcher:uninstall-launcher"),
  start: (options) => ipcRenderer.send("launcher:start", options),
  stop: () => ipcRenderer.send("launcher:stop"),
  openLocal: () => ipcRenderer.send("launcher:open-local"),
  openUrl: (url) => ipcRenderer.send("launcher:open-url", url),
  copy: (text) => ipcRenderer.send("launcher:copy", text),
  openFolder: () => ipcRenderer.send("launcher:open-folder"),
  backup: () => ipcRenderer.send("launcher:backup"),
  restoreBackup: () => ipcRenderer.send("launcher:restore-backup"),
  openBackups: () => ipcRenderer.send("launcher:open-backups"),
  minimize: () => ipcRenderer.send("window:minimize"),
  close: () => ipcRenderer.send("window:close"),
  onProgress: (callback) => ipcRenderer.on("launcher:progress", (_e, data) => callback(data)),
  onLog: (callback) => ipcRenderer.on("launcher:log", (_e, data) => callback(data)),
  onState: (callback) => ipcRenderer.on("launcher:state", (_e, data) => callback(data)),
  onInstalled: (callback) => ipcRenderer.on("launcher:installed", (_e, data) => callback(data)),
  onHostReady: (callback) => ipcRenderer.on("launcher:host-ready", (_e, data) => callback(data)),
  onHostStopped: (callback) => ipcRenderer.on("launcher:host-stopped", (_e, data) => callback(data)),
  onDiscordStatus: (callback) => ipcRenderer.on("launcher:discord-status", (_e, data) => callback(data)),
  onUpdateStatus: (callback) => ipcRenderer.on("launcher:update-status", (_e, data) => callback(data)),
  onError: (callback) => ipcRenderer.on("launcher:error", (_e, data) => callback(data)),
});
